#This is the key that will be by default displayed in the user's authentication
#app. This may be whatever you want, but we suggest making it your server name
#or some other identifier.
serverIp: "cowcraft.net"

#Sets whether or not to use the in game map based QR display.
#If this is set to true, when the user is setting up their 2FA,
#the plugin will give the user a map, and force them to then scan
#the code and insert it.
#
#If this is set to false, when the user is setting up their 2FA,
#the plugin will instead send a link to a public Google webpage which
#will display the QR code for them.
useMapBasedQR: true

permissions:
  #When a user has the below permission, the user will be forced to
  #use 2FA. When the user next joins, they will be forced to set up 2FA.

  #If not defined, by default this is 'mcauthenticator.2fa'
  2fa: "mcauthenticator.2fa"

  #When a user has the force lock permission, their 2FA may only be reset
  #from within console. This is an added level of security for those who
  #want it.

  #If not defined, by default this is 'mcauthenticator.2falock'
  forceLock: "mcauthenticator.2falock"

dataBacking:
# This plugin supports 3 independant datastorage mechanisms. At the current time, there is no way to convert between the
# two, however, this may be added in the future.

  #Types:
  # - single: Saves all data in one single file. Good for most installations
  # - directory: Saves each player in their own file within a directory
  # - mysql: Saves each player's data within a mysql database
  type: single

  #If type is single, this specifies which file to save it in.
  file: "playerData.json"

  #If type is directory, this specifies which directory to save the data in.
  directory: "playerData"

  #If type is mysql, this specifies login details
  mysql:
    url: "jdbc:mysql://localhost:3306/db"
    username: "test"
    password: "test"

#Messages section. Each message uses standard '&' color codes.
#A message can be split into multiple lines using the \n character.
messages:
  prefix: "&8[&4Auth&8] "
  authenticationPrompt: "&4This account has 2FA enabled on it. Since you are on another IP than last time, please enter the code displayed on your 2FA device."
  ipPreAuthenticated: "&7You are already authenticated since your IP matched your last log in IP."
  resetPlayer: "&7%player% has reset your 2FA. You will now asked to set up a new one."
  authenticated: "&7You have been authenticated"
  authFailed: "&4That was not a valid code. You are not yet authenticated."
  notAuthed: "&4You are not authenticated! Please enter your 2FA code."
  sendAuthCode: "&7Here is your new auth code: %code%\n&7Please enter the code generated by the device:"