#This is the key that will be by default displayed in the user's authentication
#app. This may be whatever you want, but we suggest making it your server name
#or some other identifier.
serverIp: "mc.myserver.com"

#Sets whether or not to use the in game map based QR display.
#If this is set to true, when the user is setting up their 2FA,
#the plugin will give the user a map, and force them to then scan
#the code and insert it.
#
#If this is set to false, when the user is setting up their 2FA,
#the plugin will instead send a link to a public Google webpage which
#will display the QR code for them.
useMapBasedQR: true

#If this option is true, the plugin will not factor into account the last IP of the player, and will force the player to
#log in each time they are authenticated
forceSameIPAuthentication: false

dataBacking:
# This plugin supports 3 independant datastorage mechanisms. At the current time, there is no way to convert between the
# two, however, this may be added in the future.

  #Types:
  # - single: Saves all data in one single file. Good for most installations
  # - directory: Saves each player in their own file within a directory
  # - mysql: Saves each player's data within a mysql database
  type: single

  #If type is single, this specifies which file to save it in.
  file: "playerData.json"

  #If type is directory, this specifies which directory to save the data in.
  directory: "playerData"

  #If type is mysql, this specifies login details
  mysql:
    url: "jdbc:mysql://localhost:3306/db"
    username: "test"
    password: "test"

#Messages section. Each message uses standard '&' color codes.
#A message can be split into multiple lines using the \n character.
messages:
  prefix: "&8[&4Auth&8] "
  authenticationPrompt: "&4This account has 2FA enabled on it. Please enter the code displayed on your 2FA device."
  ipPreAuthenticated: "&7You are already authenticated since your IP matched your last log in IP."
  resetPlayer: "&7%player% has reset your 2FA. You will now asked to set up a new one."
  authenticated: "&7You have been authenticated"
  authFailed: "&4That was not a valid code. You are not yet authenticated."
  notAuthed: "&4You are not authenticated! Please enter your 2FA code."
  sendAuthCode: "&7Here is your new auth code: %code%\n&7You may also view this code at\n&7%url%\n&7Enter the code generated by your device:"
  alreadyEnabled: "&cYou already have 2FA enabled!"
  otherEnable: "&4%player%&c has enabled 2FA on your account!"
  alreadyDisabled: "&cYou already have 2FA disabled!"
  disableForced: "&cYou are not permitted to disable 2FA on your account!"
  selfDisabled: "&cYou have disabled 2FA on your account."
  otherDisable: "&4%player%&c has disabled 2FA on your account!"
  otherReset: "&4%player%&c has reset the 2FA on your account!\n &4Please enter the code generated by the app from the QR code."
  resetDisabled: "&cYour account has 2FA disabled."
  resetNotAuthed: "&cYou cannot reset your account until you authenticate!"
  resetForced: "&cYou are not permitted to reset 2FA on your account!"
  selfReset: "&cYou have reset 2FA on your account. Please enter the code shown on your device from the new code."