name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
authors: ['Joseph Hirschfeld <joe@ibj.io>','aaomidi']
commands:
  auth:
    description: Command to MCAuthenticator commands